export const HTTP_EXCEPTION_ERROR_MESSAGES = {
  FORBIDDEN_RESOURCE: 'Forbidden resource',
  INVALID_JWT_TOKEN: 'Invalid token',
  MISSING_JWT_TOKEN: 'Missing JWT token',
  MISSING_DATA_PAYLOAD: 'Missing user data in payload',
  USER_DOES_NOT_EXIST: "User doesn't exist! Please input another email!",
  USER_NAME_MUST_UNIQUE: 'Username must be unique',
  USER_EMAIL_MUST_UNIQUE: "User's email must be unique",
  USER_NOT_AUTHENTICATED: 'Your are not authenticated!',
  USER_NOT_AUTHORIZED: 'Your are not authorized!',
  INVALID_PASSWORD: 'Invalid password! Please try again!',

  HOTEL_DOES_NOT_EXIST: 'Hotel does not exist',

  ROOM_DOES_NOT_EXIST: 'Room does not exist',
};

export const HTTP_EXCEPTION_ERROR_CODE = {
  // INTERNAL ERROR: 10XX
  FORBIDDEN_RESOURCE: 1000,
  VALIDATION_ERROR: 1001,
  JWT_VALIDATION_ERROR: 1002,
  MISSING_JWT_TOKEN: 1003,
  // GOTRUE AUTH: 11XX
  INVALID_PASSWORD: 1104,
  // USER: 20XX
  USER_DOES_NOT_EXIST: 2001,
  USER_UPDATE_FORBIDDEN: 2002,
  USER_UPDATE_FAILED: 2003,
  USER_FIND_FAILED: 2004,
  UNAUTHORIZED_TO_REMOVE_USER: 2005,
  USER_DELETE_FAILED: 2006,
  USER_LIST_FAILED: 2007,
  USER_CREATE_FAILED: 2008,
  USER_NAME_MUST_UNIQUE: 2009,
  USER_EMAIL_MUST_UNIQUE: 2010,
  USER_NOT_AUTHENTICATED: 2011,
  USER_NOT_AUTHORIZED:2012,
  ROOT_USER_CANNOT_BE_DELETED: 2013,
  ROOT_USER_CANNOT_REMOVE_ROLE_DEFAULT: 2014,
  //HOTEL: 21XX
  HOTEL_LIST_FAILED: 2101,
  HOTEL_TITLE_MUST_UNIQUE: 2102,
  HOTEL_CREATE_FAILED: 2103,
  HOTEL_DOES_NOT_EXIST: 2104,
  HOTEL_FIND_FAILED: 2105,
  HOTEL_UPDATE_FAILED: 2106,
  HOTEL_DELETE_FAILED: 2107,
  // ROOM: 22XX
  ROOM_LIST_FAILED: 2201,
  ROOM_NAME_MUST_UNIQUE: 2202,
  ROOM_CREATE_FAILED: 2203,
  ROOM_DOES_NOT_EXIST: 2204,
  ROOM_FIND_FAILED: 2205,
  ROOM_UPDATE_FAILED: 2206,
  ROOM_DELETE_FAILED: 2207,
};

export const HTTP_VALIDATION_ERROR_MESSAGE = {
  IsUserExisted: 'User does not exist',
};
